### ISSUE TITLE
Chat Bubbles Jitter

### ISSUE THREAD

**Issue by TheKarion** [Haplo064/ChatBubbles#23] opened 2021-12-22 21:16 UTC
This happens over yourself if your moving at all, and for most others. It might be an issue with races and their walking animations. I'm a female Roe for example and the chatbot above my head jitters a lot

**Comment by InTheBeef** [comment] 2022-01-12 01:23
I'm pretty sure this is the behavior for all races (Au Ra and Hyur here). Would absolutely love it if this were not the case.

**Comment by Haplo064** [comment] 2022-05-03 04:56
Duplicate of issue #3 , closing and tracking via that.

**Closed by Haplo064** 2022-05-03 04:56 UTC
