### ISSUE TITLE
Configure option /bub reports error and asks to restart game constantly

### ISSUE THREAD

**Issue by MCBama** [Haplo064/ChatBubbles#49] opened 2022-07-30 01:30 UTC
Attempting to configure chat bubbles reports an error and tells to restart game. Game restarts do not solve the problem however.

**Comment by Haplo064** [comment] 2022-07-30 03:01
Can you attach/send your config file?
It's under %appdata%/xiv launcher/plugin configs/chat bubbles
And then you can fix it by deleting it and restarting!

**Comment by MCBama** [comment] 2022-07-30 20:42
[ChatBubbles.json.txt](https://github.com/Haplo064/ChatBubbles/files/9227556/ChatBubbles.json.txt)

Hopefully that's the config file you're referring to (had to change json to txt to get it to upload). I take it the latest update made the old config not work?

**Comment by Equinox1906** [comment] 2022-08-20 07:21
had the same problem that dalamud kept crashing and asking me to restart. After getting rid of chatbubbles addon it finally worked again.

**Comment by MKhayle** [comment] 2022-09-15 15:40
Unsure if this issue is still ongoing because some fixes were added in the most recent update and I can't get to reproduce it, but just in case: 

- Exit the game if it's running
- Delete your config file in `%appdata%/XIVLauncher/pluginConfigs/ChatBubbles.json`
- Restart the game, and attempt to open config
- if it doesn't work, please type `/xllog`, re-attempt to open the config and report any ChatBubbles-related error which could spawn

I'm closing this issue for now, but feel free to re-open it if needed!

**Closed by MKhayle** 2022-09-15 15:40 UTC
