### ISSUE TITLE
Chat Bubbles Issue? - Steam Version Bug?

### ISSUE THREAD

**Issue by gothonarampage** [Haplo064/ChatBubbles#14] opened 2021-09-08 03:20 UTC
I have the steam version, and the plugin is installed. However, it doesn't appear to be working. I understand someone else here is also having this issue.

![chat bubble](https://user-images.githubusercontent.com/90298594/132441050-9f9bb030-03a5-432f-aba2-3e2fc7fd33b6.png)

**Comment by NoxelNyx** [comment] 2021-09-29 14:59
I am also having this issue. Also on the Steam version.

**Comment by NoxelNyx** [comment] 2021-10-17 15:44
This issue appears to be fixed in the latest version of Dalamud/Chat Bubbles.

**Comment by Haplo064** [comment] 2022-01-27 09:06
Cannot reproduce, believed to be fixed in new build.
Awaiting dalamud update before pushing out.

**Closed by Haplo064** 2022-01-27 09:06 UTC
