### ISSUE TITLE
Chat bubble vibrates when I walk or run.

### ISSUE THREAD

**Issue by BowlOfCactusJuice** [Haplo064/ChatBubbles#45] opened 2022-05-08 04:33 UTC
I think the bubbles are confused, and constantly switching between left and right orientation when I run and my head bobs... I don't know if that is a native issue with FFXIV... but yeah.

**Comment by vinajuliette** [comment] 2022-08-08 15:29
@BowlOfCactusJuice Is this a dupe of https://github.com/Haplo064/ChatBubbles/issues/3 ?

**Comment by MKhayle** [comment] 2022-09-14 14:01
This is indeed a dupe of #3, so I'm closing this for now

**Closed by MKhayle** 2022-09-14 14:01 UTC
