### ISSUE TITLE
[Bug] Chat bubble appears over the wrong player

### ISSUE THREAD

**Issue by fournm** [Haplo064/ChatBubbles#26] opened 2022-01-15 02:38 UTC
If you type a message with a `<t>` pointing at another player, the bubble appears over that other player's head. It doesn't matter if the target variable is at the front or somewhere in the middle of the message.

**Comment by Haplo064** [comment] 2022-01-27 09:02
Cannot reproduce, believed to be fixed in new build.
Awaiting dalamud update before pushing out.

**Closed by Haplo064** 2022-01-27 09:02 UTC

**Comment by TwistedAkai** [comment] 2022-04-05 23:40
I'm getting this when using <2> and so on. v1.3.2.2
