### ISSUE TITLE
Installed through XIV Launcher. Chat bubbles not appearing.

### ISSUE THREAD

**Issue by Calibrumm** [Haplo064/ChatBubbles#11] opened 2021-08-20 15:23 UTC
title. I cross-checked my settings with my friend who has them working and disabled all other plugins but still nothing. the only difference between his install and mine is that I own FFXIV through Steam and he doesn't, but I cant imagine that's an issue as all other plugins work.

**Comment by gothonarampage** [comment] 2021-09-08 03:07
I too am having this issue, and also have the steam version.

**Comment by Haplo064** [comment] 2022-01-27 09:04
Cannot reproduce, believed to be fixed in new build.
Awaiting dalamud update before pushing out.

**Closed by Haplo064** 2022-01-27 09:04 UTC
