### ISSUE TITLE
[API4][Bug Report] Hide Bubble config not save

### ISSUE THREAD

**Issue by Lanselotto** [Haplo064/ChatBubbles#16] opened 2021-09-21 11:33 UTC
The plugin save the hide bubble option correctly on the json config file but does not read the information at startup cause
`_hide = _configuration.Hide` is missing in the constructor.

**Comment by Haplo064** [comment] 2022-01-27 09:03
Cannot reproduce, believed to be fixed in new build.
Awaiting dalamud update before pushing out.

**Closed by Haplo064** 2022-01-27 09:03 UTC
