### ISSUE TITLE
Specific Emote Bubble Location

### ISSUE THREAD

**Issue by SonyUSA** [Haplo064/ChatBubbles#12] opened 2021-08-26 06:18 UTC
There is one specific emote (sorry I just started I don't know which) that displays text that places the bubble over your own head. Likely because the %t is not the first word. The text is something like:

"The sight of X springs a question to Y..."

May need a special parser exception for that emote to pull the target from the 4th word... :)

**Comment by Haplo064** [comment] 2022-01-27 09:04
Cannot reproduce, believed to be fixed in new build.
Awaiting dalamud update before pushing out.

**Closed by Haplo064** 2022-01-27 09:04 UTC
